---
abstract: 'Object class for manipulating and generating E-books'
author:
  - 'Zed Pobre <zed@debian.org>'
build_requires:
  DBD::SQLite: '1.20'
configure_requires:
  Module::Build: '0.42'
dynamic_config: 1
generated_by: 'Module::Build version 0.421, CPAN::Meta::Converter version 2.142060'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: EBook-Tools
provides:
  EBook::Tools:
    file: lib/EBook/Tools.pm
    version: v0.5.4
  EBook::Tools::BISG:
    file: lib/EBook/Tools/BISG.pm
    version: v0.5.4
  EBook::Tools::EReader:
    file: lib/EBook/Tools/EReader.pm
    version: v0.5.2
  EBook::Tools::IMP:
    file: lib/EBook/Tools/IMP.pm
    version: v0.5.0
  EBook::Tools::LZSS:
    file: lib/EBook/Tools/LZSS.pm
    version: v0.5.0
  EBook::Tools::MSReader:
    file: lib/EBook/Tools/MSReader.pm
    version: v0.5.0
  EBook::Tools::Mobipocket:
    file: lib/EBook/Tools/Mobipocket.pm
    version: v0.5.0
  EBook::Tools::PalmDoc:
    file: lib/EBook/Tools/PalmDoc.pm
    version: v0.5.2
  EBook::Tools::Unpack:
    file: lib/EBook/Tools/Unpack.pm
    version: v0.5.0
requires:
  Archive::Zip: '1.16'
  Bit::Vector: '6.4'
  Compress::Zlib: '1'
  Config::IniFiles: '2'
  DBI: '1.614'
  Data::UUID: '1'
  Date::Manip: '5.44'
  Encode::Detect: '1'
  File::MimeInfo: '0.13'
  File::Slurp: '9999'
  File::Which: '0'
  HTML::Entities: '1'
  HTML::TextToHTML: '2.44'
  HTML::TreeBuilder: '3.19'
  Image::Size: '3.1'
  LWP::Protocol::https: '0'
  Lingua::EN::NameParse: '1'
  List::MoreUtils: '0.21'
  Mojo::DOM: '0'
  Palm::PDB: '1'
  Palm::Raw: '1'
  String::CRC32: '1'
  Tie::IxHash: '1.21'
  Time::Local: '1.18'
  URI::Escape: '1'
  XML::Twig: '3.32'
  perl: v5.10.1
  version: '0.74'
resources:
  license: http://opensource.org/licenses/gpl-2.0.php
version: v0.5.4
